---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blah-deployment
spec:
  selector:
    matchLabels:
      app: blah-pods
  replicas: 2
  template:
    metadata:
      labels:
        app: blah-pods
    spec:
      containers:
        - name: blah-web
          image: blah-webapp:v1
---
apiVersion: v1
kind: Service
metadata:
  name: blah-service
spec:
  selector:
    app: blah-pods
  ports:
    - name: http
      port: 80
      nodePort: 31080
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
spec:
  containers:
    - name: curl
      image: blah-webapp:v1
      command:
        - /bin/bash
      args:
        - -c
        - |
          while true; do
            echo hello
            sleep 10;
          done
